### ISSUE TITLE
can't get a single version to work

### ISSUE THREAD

**Issue by krecicki** [Mobile-Artificial-Intelligence/maid#445]
I tried to new .apk and the building our own. We keep getting this error when we try to chat.

```
-------------- PROCESS STARTED (5124) for package com.biprep.sherpa ----------------------------
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Build fingerprint: 'samsung/c1qsqw/c1q:13/TP1A.220624.014/N981USQS6HXC1:user/release-keys'
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Revision: '10'
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  ABI: 'arm64'
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Processor: '4'
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Timestamp: 2024-03-23 13:32:35.109575688-0700
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Process uptime: 20s
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Cmdline: com.biprep.sherpa
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  pid: 4851, tid: 5113, name: DartWorker  >>> com.biprep.sherpa <<<
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  uid: 10352
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000000
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A  Cause: null pointer dereference
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x0  00000076007998b9  x1  0000000000000000  x2  0000000000047208  x3  00000076007998d8
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x4  0000000000000047  x5  0000000000000004  x6  b4000078bca10728  x7  00000076007998b8
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x8  0000000000000001  x9  b4000078fca10150  x10 000000778cd73b78  x11 b4000078fca10150
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x12 0000000000000000  x13 0000000000000008  x14 0000007600799890  x15 000000778cd73c60
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x16 0000808100008081  x17 fffffffffffffea0  x18 0000007712360000  x19 0000007727111cd8
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x20 0000007600795f49  x21 b400007ac7f93ee0  x22 0000007600008081  x23 b4000078fca10150
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x24 0000007600015f11  x25 000000778cc93000  x26 b4000078fca10150  x27 000000760050ede0
2024-03-23 13:32:35.847  5120-5120  DEBUG                   crash_dump64                         A      x28 0000000800000076  x29 000000778cd73e88
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A      lr  000000772710d238  sp  000000778cc93000  pc  000000772710d240  pst 0000000020001000
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A  backtrace:
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #00 pc 00000000002f3240  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #01 pc 000000000049f090  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #02 pc 00000000001d19e8  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #03 pc 00000000001d1858  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #04 pc 00000000001d0114  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #05 pc 00000000001cbc70  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #06 pc 000000000049f710  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #07 pc 00000000001cab00  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #08 pc 000000000049f090  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #09 pc 00000000001d19e8  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #10 pc 00000000001d1858  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #11 pc 00000000001d0114  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #12 pc 00000000001cbc70  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #13 pc 00000000001cbbd0  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #14 pc 00000000001cb43c  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #15 pc 00000000001cb320  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #16 pc 00000000001cb2e4  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #17 pc 00000000001ccd1c  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #18 pc 00000000001cccc4  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #19 pc 00000000001b3030  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libapp.so (BuildId: bca64abf5b0a127334758117194a2c4b)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #20 pc 00000000006eac64  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libflutter.so (BuildId: bc288ad17fb9e6730b9a943bacfad667e3c5a1f3)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #21 pc 00000000006f7104  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libflutter.so (BuildId: bc288ad17fb9e6730b9a943bacfad667e3c5a1f3)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #22 pc 00000000006fcbf0  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libflutter.so (BuildId: bc288ad17fb9e6730b9a943bacfad667e3c5a1f3)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #23 pc 00000000006fc978  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libflutter.so (BuildId: bc288ad17fb9e6730b9a943bacfad667e3c5a1f3)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #24 pc 0000000000796c54  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libflutter.so (BuildId: bc288ad17fb9e6730b9a943bacfad667e3c5a1f3)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #25 pc 0000000000758434  /data/app/~~Ie4_wl75UzjKjNJl98CHDQ==/com.biprep.sherpa--hO07Dm6SJ1yS11eMQA2Ng==/lib/arm64/libflutter.so (BuildId: bc288ad17fb9e6730b9a943bacfad667e3c5a1f3)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #26 pc 00000000000bb728  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 870560a8376a70249f9e9a7b480cc02f)
2024-03-23 13:32:35.848  5120-5120  DEBUG                   crash_dump64                         A        #27 pc 000000000005501c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 870560a8376a70249f9e9a7b480cc02f)
2024-03-23 13:32:35.884  1268-5133  DropBoxManagerService   system_server                        I  add tag=data_app_native_crash isTagEnabled=true flags=0x2
2024-03-23 13:32:35.908  1268-5132  ContextImpl             system_server                        W  Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1252 com.android.server.am.AppErrors.crashApplicationInner:722 com.android.server.am.AppErrors.crashApplication:598 com.android.server.am.ActivityManagerService.handleApplicationCrashInner:10496 com.android.server.am.NativeCrashListener$NativeCrashReporter.run:88 
2024-03-23 13:32:35.908  1268-5132  ActivityManager         system_server                        W  crash : com.biprep.sherpa,10352
2024-03-23 13:32:35.918  1268-5132  WindowManager           system_server                        W  Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.requestTransitionAndLegacyPrepare:6509 com.android.server.wm.Task.finishTopCrashedActivityLocked:6797 com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$19:2688 com.android.server.wm.RootWindowContainer.$r8$lambda$4nB35TzseTo6qyVD9NxDieoJN1Y:0 
2024-03-23 13:32:35.929  1268-5132  ActivityTaskManager     system_server                        W  Failed to send top-resumed=false to ActivityRecord{23f287a u0 com.biprep.sherpa/.MainActivity} t68 f}}
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:662)
                                                                                                    	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2031)
                                                                                                    	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
                                                                                                    	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
                                                                                                    	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:85)
                                                                                                    	at com.android.server.wm.ActivityRecord.scheduleTopResumedActivityChanged(ActivityRecord.java:1705)
                                                                                                    	at com.android.server.wm.ActivityTaskSupervisor.updateTopResumedActivityIfNeeded(ActivityTaskSupervisor.java:2510)
                                                                                                    	at com.android.server.wm.TaskDisplayArea.positionChildTaskAt(TaskDisplayArea.java:602)
                                                                                                    	at com.android.server.wm.TaskDisplayArea.positionChildAt(TaskDisplayArea.java:537)
                                                                                                    	at com.android.server.wm.Task.moveToFrontInner(Task.java:6053)
                                                                                                    	at com.android.server.wm.Task.moveToFront(Task.java:6019)
                                                                                                    	at com.android.server.wm.Task.moveToFront(Task.java:5953)
                                                                                                    	at com.android.server.wm.Task.adjustFocusToNextFocusableTask(Task.java:3244)
                                                                                                    	at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:4055)
                                                                                                    	at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:3966)
                                                                                                    	at com.android.server.wm.Task.finishTopCrashedActivityLocked(Task.java:6798)
                                                                                                    	at com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$19(RootWindowContainer.java:2688)
                                                                                                    	at com.android.server.wm.RootWindowContainer.$r8$lambda$4nB35TzseTo6qyVD9NxDieoJN1Y(Unknown Source:0)
                                                                                                    	at com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda16.accept(Unknown Source:10)
                                                                                                    	at com.android.server.wm.Task.forAllTasks(Task.java:4091)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2021)
                                                                                                    	at com.android.server.wm.RootWindowContainer.finishTopCrashedActivities(RootWindowContainer.java:2687)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(ActivityTaskManagerService.java:8039)
                                                                                                    	at com.android.server.am.AppErrors.handleAppCrashLSPB(AppErrors.java:1047)
                                                                                                    	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:879)
                                                                                                    	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:748)
                                                                                                    	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:598)
                                                                                                    	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:10496)
                                                                                                    	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:88)
2024-03-23 13:32:35.929  1268-5132  WindowManager           system_server                        W  Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.prepareAppTransition:6484 com.android.server.wm.ActivityRecord.finishIfPossible:4151 com.android.server.wm.ActivityRecord.finishIfPossible:3966 com.android.server.wm.Task.finishTopCrashedActivityLocked:6798 
2024-03-23 13:32:35.931  1268-5132  ActivityTaskManager     system_server                        W  Exception thrown during pause
                                                                                                    android.os.DeadObjectException
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:662)
                                                                                                    	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2031)
                                                                                                    	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
                                                                                                    	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
                                                                                                    	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:69)
                                                                                                    	at com.android.server.wm.TaskFragment.schedulePauseActivity(TaskFragment.java:1986)
                                                                                                    	at com.android.server.wm.TaskFragment.startPausing(TaskFragment.java:1912)
                                                                                                    	at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:4191)
                                                                                                    	at com.android.server.wm.ActivityRecord.finishIfPossible(ActivityRecord.java:3966)
                                                                                                    	at com.android.server.wm.Task.finishTopCrashedActivityLocked(Task.java:6798)
                                                                                                    	at com.android.server.wm.RootWindowContainer.lambda$finishTopCrashedActivities$19(RootWindowContainer.java:2688)
                                                                                                    	at com.android.server.wm.RootWindowContainer.$r8$lambda$4nB35TzseTo6qyVD9NxDieoJN1Y(Unknown Source:0)
                                                                                                    	at com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda16.accept(Unknown Source:10)
                                                                                                    	at com.android.server.wm.Task.forAllTasks(Task.java:4091)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2028)
                                                                                                    	at com.android.server.wm.WindowContainer.forAllTasks(WindowContainer.java:2021)
                                                                                                    	at com.android.server.wm.RootWindowContainer.finishTopCrashedActivities(RootWindowContainer.java:2687)
                                                                                                    	at com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(ActivityTaskManagerService.java:8039)
                                                                                                    	at com.android.server.am.AppErrors.handleAppCrashLSPB(AppErrors.java:1047)
                                                                                                    	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:879)
                                                                                                    	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:748)
                                                                                                    	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:598)
                                                                                                    	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:10496)
                                                                                                    	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:88)
2024-03-23 13:32:35.936  1268-5132  WindowManager           system_server                        W  Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.prepareAppTransition:6484 com.android.server.wm.TaskFragment.resumeTopActivity:1583 com.android.server.wm.TaskFragment.resumeTopActivity:1307 com.android.server.wm.Task.resumeTopActivityInnerLocked:6451 
2024-03-23 13:32:35.945  1268-5132  WindowManager           system_server                        W  Execute app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.RootWindowContainer.executeAppTransitionForAllDisplay:2580 com.android.server.wm.ActivityTaskSupervisor.reportResumedActivityLocked:2287 com.android.server.wm.ActivityRecord.completeResumeLocked:6987 com.android.server.wm.TaskFragment.resumeTopActivity:1743 com.android.server.wm.TaskFragment.resumeTopActivity:1307 
2024-03-23 13:32:35.954  1268-1315  WindowManager           system_server                        W  Execute app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.Task.executeAppTransition:7870 com.android.server.wm.RootWindowContainer.lambda$resumeFocusedTasksTopActivities$20:2750 com.android.server.wm.RootWindowContainer.$r8$lambda$T5O2b-2Pin2YrxYnsz1zP_DLpiQ:0 com.android.server.wm.RootWindowContainer$$ExternalSyntheticLambda17.accept:13 com.android.server.wm.Task.forAllRootTasks:4097 
2024-03-23 13:32:35.955  1268-1315  WindowManager           system_server                        W  Execute app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.Task.executeAppTransition:7870 com.android.server.wm.TaskFragment.resumeTopActivity:1354 com.android.server.wm.TaskFragment.resumeTopActivity:1307 com.android.server.wm.Task.resumeTopActivityInnerLocked:6451 com.android.server.wm.Task.resumeTopActivityUncheckedLocked:6352 
2024-03-23 13:32:35.999  1268-1315  WindowManager           system_server                        W  Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.prepareAppTransition:6484 com.android.server.wm.ActivityRecord.finishIfPossible:4151 com.android.server.wm.ActivityClientController.finishActivity:522 android.app.IActivityClientController$Stub.onTransact:711 
2024-03-23 13:32:36.017  1268-7863  WindowManager           system_server                        W  Prepare app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN, TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.DisplayContent.prepareAppTransition:6493 com.android.server.wm.DisplayContent.prepareAppTransition:6484 com.android.server.wm.TaskFragment.resumeTopActivity:1562 com.android.server.wm.TaskFragment.resumeTopActivity:1307 com.android.server.wm.Task.resumeTopActivityInnerLocked:6451 
2024-03-23 13:32:36.021  1268-7863  WindowManager           system_server                        W  Execute app transition: mNextAppTransitionRequests=[TRANSIT_CLOSE, TRANSIT_CLOSE, TRANSIT_OPEN, TRANSIT_CLOSE, TRANSIT_CLOSE], mNextAppTransitionFlags=TRANSIT_FLAG_KEYGUARD_GOING_AWAY_TO_LAUNCHER_WITH_IN_WINDOW_ANIMATIONS | TRANSIT_FLAG_APP_CRASHED, displayId: 0 Callers=com.android.server.wm.RootWindowContainer.executeAppTransitionForAllDisplay:2580 com.android.server.wm.ActivityTaskSupervisor.reportResumedActivityLocked:2287 com.android.server.wm.ActivityRecord.completeResumeLocked:6987 com.android.server.wm.TaskFragment.resumeTopActivity:1743 com.android.server.wm.TaskFragment.resumeTopActivity:1307 
2024-03-23 13:32:36.023  1268-7863  WindowManager           system_server                        D  Loading animation for app transition. transit=TRANSIT_OLD_CRASHING_ACTIVITY_CLOSE enter=true frame=Rect(0, 0 - 1080, 2400) insets=Rect(0, 92 - 0, 135) surfaceInsets=Rect(0, 0 - 0, 0)
2024-03-23 13:32:36.024  8443-8443  SDHMS:BarT...r:AppError com.sec.android.sdhms                I  update AppError : uid=10352, pkg=com.biprep.sherpa, errorType=crash
---------------------------- PROCESS ENDED (4851) for package com.biprep.sherpa ----------------------------
```

**Comment by danemadsen** [comment]
com.biprep.sherpa how on earth are you getting that as an app id? I changed all those ages ago?

**Comment by danemadsen** [comment]
what was your issue?
